### ISSUE TITLE
an error occurs related to request's decoration

### ISSUE THREAD

**Issue by gtolarc** [fastify/fastify-jwt#110]
Currently, an error occurs related to request's decoration. Perhaps it is related to the following content. Can you fix it?
https://github.com/fastify/fastify/pull/2558

**Comment by Eomm** [comment]
Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.

**Comment by gtolarc** [comment]
Sorry to confuse you.
The problem was solved. https://github.com/fastify/fastify/pull/2597
