### ISSUE TITLE
Can we namespace this to support multiple JWT verification providers?

### ISSUE THREAD

**Issue by gboston** [fastify/fastify-jwt#111]
I would like to be able to verify the JWT token but these can come from multiple providers.
Is this something that is already possible?

**Comment by Eomm** [comment]
Merging in #112

**Comment by simoneb** [comment]
@Eomm @climba03003 @gboston is this addressed now, as mentioned earlier? #112 . Can we close this?

**Comment by climba03003** [comment]
> 
> 
> @Eomm @climba03003 @gboston is this addressed now, as mentioned earlier? #112 . Can we close this?

@simoneb #112 is not merged. So, it is a out-standing issue.

**Comment by simoneb** [comment]
Good point, I saw it closed and I assumed it was merged, but it wasn't. Okay then, let's keep this open.
