### ISSUE TITLE
Document how to support JWKS

### ISSUE THREAD

**Issue by simoneb** [fastify/fastify-jwt#132]
## 🚀 Feature Proposal

Support for JWKS

## Motivation

Many services (e.g. AWS Cognito, Auth0) support JWKS and this plugin should be able to verify/decode tokens generated by those services.

We are introducing support for JWKS in [fast-jwt](https://github.com/nearform/fast-jwt/issues/63) via https://github.com/nearform/jwks-fetch, which has been extracted from https://github.com/nearform/fastify-auth0-verify. In the same way, we could support JWKS in this package.

**Comment by mcollina** [comment]
The best approach would be for fastify-jwt to provide a hook/function that is called to retrieve the jwks.

**Comment by simoneb** [comment]
Support for jwks will not be build into this library but it can be added by integrating with https://github.com/nearform/get-jwks/. It would be worth updating the docs in this repo to show how to do it.
