### ISSUE TITLE
alllow secret to return a Promise

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-jwt#139]
## 🚀 Feature Proposal

Here is an example:

```js
const fastify = require('fastify')()
const jwt = require('fastify-jwt')
const request = require('request')

fastify.register(jwt, {
  secret: async function (request, reply) {
    // do something async
    return 'supersecret'
  }
})
```

**Comment by simoneb** [comment]
When this is done we should remember to:

- update the docs to show a more correct async pattern https://github.com/fastify/fastify-jwt#verifying-with-jwks
- update get-jwks docs and integration tests for the same reason
