### ISSUE TITLE
Named imports do not work with TypeScript

### ISSUE THREAD

**Issue by kibertoad** [fastify/fastify-jwt#150]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.x

### Node.js version

14.x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Despite TS types claiming that this import is fine:

```
import { fastifyJWT } from 'fastify-jwt'

app.register(fastifyJWT, {
  secret: secret
})
```

, it actually isn't and throws an error that not a plugin is being registered.

### Steps to Reproduce

Try to import plugin using named import in TypeScript

### Expected Behavior

Named import should work.

**Comment by mcollina** [comment]
would you send a fix?

**Comment by kibertoad** [comment]
Will do. Infamous triplet should suffice, I think.

**Comment by Manubi** [comment]
In may case it complains about the difference in type Callback vs PluginAsync. Works if I type it any...

<img width="906" alt="CleanShot 2021-12-21 at 17 20 17@2x" src="https://user-images.githubusercontent.com/20935138/146963726-cf421714-c722-4118-9aa6-e752d3b82cdd.png">
