### ISSUE TITLE
Verifying a JWT from a signed cookie

### ISSUE THREAD

**Issue by drewrawitz** [fastify/fastify-jwt#151]
I'm currently using both `fastify-jwt` and `fastify-cookie` to store my access token. 

```
app.register(jwt, {
  secret: JWT_SECRET,
  cookie: {
    cookieName: COOKIE_ACCESS_TOKEN,
  },
});

app.register(cookie, {
  secret: COOKIE_SECRET,
});
```

The one caveat is that the cookie that I'm storing is **signed**.  The main issue with that is that I can't use the following snippet to verify the JWT token:

```
request.jwtVerify()
```

because it will always be a malformed JWT token. I need to verify the unsigned version. So I had to imeplement my own verification function:

```
/**
  * Verify JWT Access Token
  */
const verifyAccessToken = async () => {
  const accessToken = request.cookies[COOKIE_ACCESS_TOKEN];
  const unsignedAccessToken = request.unsignCookie(accessToken);

  if (!unsignedAccessToken.value) {
    return null;
  }

  return app.jwt.verify(unsignedAccessToken.value);
};
```

That works great, but I really want to be able to use the `jwtVerify()` helper so that `request.user` gets populated from the `decorateRequest` API.

What do you guys think about planning for that in the verify logic? Maybe when registering the plugin, we could pass in a boolean to indicate if the cookie is signed or not:

```
cookie: {
  cookieName: COOKIE_ACCESS_TOKEN,
  signed: true
},
```

Has anyone run into this before? 

**Edit:** I just created a PR to demonstrate what I had in mind. Let me know what you guys think: https://github.com/fastify/fastify-jwt/pull/152

**Comment by turbobuilt** [comment]
Hey everybody, I'm not an expert on this, what is the point of a signed cookie?  Isn't the JWT signed already somehow?  I want to make sure I don't screw up my security model by not signing my cookie.  I created my jwt like this: `(reply as any).jwtSign({guid: user.guid}, { expiresIn: "3 days"});`.  Then I set it like this:
```
(reply as any).setCookie('token', token, {
        path: '/',
        httpOnly: true,
        sameSite: true // alternative CSRF protection
    });
```

If I do signed: true, it complains that it doesn't work.  I think the documentation should be updated to say whether or not we need to sign our cookies for security!  Thank you for all the hard work.

**Comment by simoneb** [comment]
The cookie is just a transport mechanism for the token. The token is signed, the cookie can be signed too. This library supports getting the token from a cookie. If you sign the cookie, then you need to inform this library that the cookie is signed, so it will try to unsign the cookie before processing the token. Makes sense?

**Comment by turbobuilt** [comment]
@simoneb Thank you so much for the help!  I guess I need to brush up on my coding skills!  Maybe we should put this in the documentation somewhere to help n00bs like me :)

**Comment by simoneb** [comment]
@turbobuilt there's an [example using cookies in the readme](https://github.com/fastify/fastify-jwt#example-using-cookie), the changes required to use a signed cookie are minimal. If you can't get it to work please post a repro and somebody will help out.
