### ISSUE TITLE
Customize how JWT is received from headers

### ISSUE THREAD

**Issue by danthegoodman1** [fastify/fastify-jwt#153]
## 🚀 Feature Proposal

Right now we are forced to use the header format `Authorization: Bearer [token]`. It would be nice if we could customize the function used to fetch the `[token]` so we could remove the `Bearer` part, or use a different header

## Motivation

Flexibility in usage

## Example

```js
server.addHook("onRequest", async (request, reply) => {
    try {
      await request.jwtVerify({
        vverifyFunc: (request, reply) => {
          return request.headers['Auth']
        }
      })
    } catch (err) {
      reply.send(err)
    }
  })
```

**Comment by mcollina** [comment]
I would prefer this to be in the options of the plugin. Anyway, 
would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by simoneb** [comment]
@danthegoodman1 check out https://github.com/fastify/fastify-jwt#verify-options, the `extractToken` option.

**Comment by danthegoodman1** [comment]
> @danthegoodman1 check out https://github.com/fastify/fastify-jwt#verify-options, the `extractToken` option.

Looks like I can't read! I'll test right now

**Comment by danthegoodman1** [comment]
@simoneb Was right, here is what I used
```js
server.register(fastifyJWT, {
  secret: jwtSecret,
  verify: {
    extractToken: (req) => {
      const tok: string = req.headers['auth'] as string
      return tok
    }
  },
  messages: {
    badRequestErrorMessage: 'Format is `auth: [token]`'
  }
})
```
