### ISSUE TITLE
cant decode token and retrieve username

### ISSUE THREAD

**Issue by sensorario** [fastify/fastify-jwt#16]
As reported here:

https://stackoverflow.com/questions/49831398/retrieve-username-from-jwt-token-using-fastify

I am able to create a jwt token:

    fastify.post('/signup', (req, reply) => {
      const token = fastify.jwt.sign({
        payload,
      })
      reply.send({ token })
    })

that can return something like:

>{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MjM3MDgyMzF9.HZqqiL7wwPaEQihUGoF7Y42Ia67HgKJ-1Ms38Nvcsmw"}

but if I try to decode the username frmo token

    fastify.get('/decode', async (request, reply) => {
      const auth = request.headers.authorization;
      const token = auth.split(' ')[1]
      fastify.jwt.verify(token, (err, decoded) => {
        if (err) fastify.log.error(err)
        fastify.log.info('username : ' + decoded.username)
        reply.send({
          foo: decoded,
        })
      })
    })

the response is:

> {"foo":{"iat":1523660987}}

**Comment by delvedor** [comment]
Can you upload a full example that reproduces the issue?

**Comment by sensorario** [comment]
No sorry. But I'd found the solution (or the problem) ^_^. In `/signup` endpoint I've sent `{payload:{username:"foo"}}`.

In the wrong code `fastify.log.info('username : ' + decoded.username)` I've fixed with `fastify.log.info('username : ' + decoded.payload.username)`
