### ISSUE TITLE
Can I use an aync version `formatUser` method?

### ISSUE THREAD

**Issue by laozhu** [fastify/fastify-jwt#161]
When I use formatUser, I want to get cached user object from redis or db, but the process is async.
With the types-hint, maybe I can't do this with formatUser.

**Comment by mcollina** [comment]
I would recommend doing that in a separate Fastify hook. The typing hooks are correct, that method must be sychronous.

**Comment by laozhu** [comment]
Thank you, Can I get user object from cache or db in prehandler hook? I don't want to put the logic in route handler, because many routes have the same needs. Or maybe I can decorateRequest with a async utility to get current user, is this better practice?

**Comment by mcollina** [comment]
> Thank you, Can I get user object from cache or db in prehandler hook? 

That's my recommendation.
