### ISSUE TITLE
Property 'user' does not exist on type 'FastifyRequest<OAuthInput, Server, IncomingMessage>'.

### ISSUE THREAD

**Issue by Lilja** [fastify/fastify-jwt#173]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.14.1

### Plugin version

3.0.8

### Node.js version

v14.15.5

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

N/A

### Description

I'm getting a typescript error, it's surely due to that I've split up certain logical things from each other as plugins into multiple files.

```ts
// routes/auths.ts
import { FastifyInstance } from 'fastify'
import fp from "fastify-plugin"
export default fp(function(fastify: FastifyInstance, opts: any, done: any) {
    logger.debug({}, "fastify-cookie")
    fastify.register(cookie);
    logger.debug({fastify}, "Registering custom JWT auth")
    fastify.register(fastifyJwt, {
        secret,
        cookie: {
            cookieName: "token",
            signed: false,
        },
    })

    logger.debug({}, "Decorating custom auth fn")
    fastify.decorate("authenticate", async function(request: any, reply: any) {
        try {
            await request.jwtVerify()
        } catch (err) {
            reply.send(err)
        }
    })
    logger.debug({}, "registering auth plugin")
    fastify.decorate('jwtVerification', async function(
        request: FastifyRequest,
        reply: FastifyReply
    ) {
        const jwtInfo = request.user
        if (!jwtInfo.marketingAccessToken) {
            throw new Error(MARKETING_ACCOUNT_NOT_CONNECTED().message)
        }
    });
});
```

```ts
// src/routes/oauth.ts
import { FastifyInstance } from 'fastify'
import fp from "fastify-plugin"
export default fp(function(fastify: FastifyInstance, opts: any, done: any) {

    const auth = {preValidation: [(fastify as any).authenticate]}

    fastify.post<OAuthInput>(route("/submitCodeLogin"), async (request, reply) => {
        const authInfo = request.user as AuthInfo // src/routes/oauth.ts(42,34): error TS2339: Property 'user' does not exist on type 'FastifyRequest<OAuthInput, Server, IncomingMessage>'.
    });
}
```

```ts
import auth from "./routes/auth"
import oauthRoutes from './routes/oauth
import Fastify, { FastifyInstance } from 'fastify'
const server: FastifyInstance = Fastify({ logger: true })

logger.debug({}, "Auth routes")
server.register(auth)

logger.debug({}, "Oauth routes")
server.register(oauthRoutes)
```

I guess it's due to the fact that I'm using multiple plugins for each file? I don't have a hard requirement on doing so. But from the documentation I've read from I don't really understand what is the best course of action here, so I made a plugin for each file.

### Steps to Reproduce

N/A see above

**Comment by Lilja** [comment]
I solved this by having a second look into other people's github repos. 

Basically, I removed everything that was a plugin that didn't do any `.decorate` functions.
```ts
export default fp(function(fastify: FastifyInstance, opts: any, done: any) {
```

to

```ts
export default async function(fastify: FastifyInstance) {
```

> The Fastify instance passed on to the function is the latest state of the external Fastify instance the plugin was declared on, allowing access to variables injected via decorate by preceding plugins according to the order of registration. This is useful in case a plugin depends on changes made to the Fastify instance by a preceding plugin i.e. utilizing an existing database connection to wrap around it.

Using `.decorate` and expect other parts to use it? wrap with `fastify-plugin`.

**Comment by simoneb** [comment]
You may want to check out this section of the docs: https://www.fastify.io/docs/master/Plugins/#handle-the-scope
