### ISSUE TITLE
Expose logic to read and/or decode JWT token from the request

### ISSUE THREAD

**Issue by markrzen** [fastify/fastify-jwt#176]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Expose logic to read and/or decode JWT token from the request. I am looking for feedback if this would be acceptable, and if so, any preference between exposing the functionality via request decoration or through a require-able file?
(See examples)

### Motivation

Allow for plugin extension, such as [fastify-auth0-verify](https://github.com/nearform/fastify-auth0-verify/blob/master/index.js#L153-L165).

Right now plugins extending from this one, must re-write the logic to lookup and decode the token.

### Example

```js
// Decoration
request.jwtLookupToken
request.jwtDecode

// Require-able file
const {read, decode} = require('fastify-jwt/lib/token');
```

**Comment by Eomm** [comment]
Could you share a usage example?

**Comment by markrzen** [comment]
@Eomm Here is the draft PR for the change, hopefully this makes more sense:
https://github.com/fastify/fastify-jwt/pull/178

**Comment by markrzen** [comment]
@Eomm Checking in again, any thoughts on the idea?

**Comment by markrzen** [comment]
🦗 🦗

**Comment by Eomm** [comment]
> 🦗 🦗

Is this the echo? 😄 

Checking your PR 👍🏽

**Comment by markrzen** [comment]
@Eomm Haha, I was hoping that didn't come off poorly. It was an echo :) If the PR concept makes sense, I will happily switch over to making it more real (tests, etc).

**Comment by Eomm** [comment]
Yes, it totally makes sense and your solution is fine!
I left some comments on the PR 👍🏽  I will be faster this time 😄 

Thank you for the patience

**Comment by markrzen** [comment]
Fantastic. I will finish up on the PR. Expect changes/responses in a few hours.

Thanks @Eomm !

**Comment by markrzen** [comment]
Behind schedule. Fixed some of the PR comments, but need to grok the test organization a bit more to make sure I don't get off your patterns.
