### ISSUE TITLE
JWT in reply header or cookie?

### ISSUE THREAD

**Issue by dbauszus-glx** [fastify/fastify-jwt#18]
Fastify being an opinionated web framework may I ask for your opinion on how to use JWT?

I just switched from sessions to JWT. This was easily done by storing the JWT as a cookie which I sent with the reply from the authorization middleware.

I set cookie with a reply.redirect('/') from the login route.

The fastify-jwt documentation shows how to put the token as bearer in the Authentication header. How would I use this with reply.redirects()?

Is there a smart way to set the header for all calls from a client application or would I have to manually change every xhr request?

Given that the cookie method works well are there any obvious downsides which I am not seeing?

**Comment by dbauszus-glx** [comment]
I have this working with cookies but don't think that is the best approach. Some libraries in my project use the fetch API and I cannot control whether a cookie is send.

I am also concerned that the cookie is send both way while I really need the token only on the request and not on the server response.

Then there is the issue with securing a cookie, I need to make sure that the cookie expires as well as the token. I also need to protect the cookie being accessed from script while I may need the token in the script.

Right now I am thinking of putting the token into a custom data attribute on either the head or body of the document.

**Comment by mandaputtra** [comment]
@mcollina I stored JWT on cookies like this

```
if (pass) {
    const secret = req.generateSecretCSRF
    const tokenCSRF = reply.createTokenCSRF(secret)
    const token = this.jwt.sign({
      userId: user._id,
      role: user.role,
      tokenCSRF,
    })
    user.password = ''

    // generate session secret for crsf
    req.session.scrt = secret
    reply
      .setCookie('tks', token, {
        path: '/'
      })
      .code(200)
      .send({data: user})
  } else {
    reply.code(401).send('your email or password wrong!')
  }
```

I think the `request.verifyJwt()` itself are checking the header whether there is a `headersauthorization` or not will

```
fastify.decorate('verifyjwt', async (request, reply) => {
    try {
      await fastify.jwt.verify(request.cookies.tks)
    } catch (error) {
      reply.code(401).send(error)
    }
  })
```

is this look okay to you or need improvement? i would love to create an example.

**Comment by mcollina** [comment]
It's ok, go for it!

**Comment by daniandl** [comment]
```
fastify.decorate('verifyjwt', async (request, reply) => {
    try {
      await fastify.jwt.verify(request.cookies.tks)
    } catch (error) {
      reply.code(401).send(error)
    }
  })
```
This doesn't continue the request for me sadly, even if I use next(). My editor also tells me that `fastify.jwt.verify` isn't a Promise, so using await might be the wrong approach.

I also tried setting the Authorization header before calling `jwtVerify()` but I still get the no authorization in req.headers..
```
req.headers.Authorization = `Bearer ${req.cookies.jwt}`
const jwt = await req.jwtVerify()
```

Any help? :)

**Comment by Eomm** [comment]
Added this feature in #81 

Closing
