### ISSUE TITLE
Remove JwtHeader type definition after fast-jwt release

### ISSUE THREAD

**Issue by radomird** [fastify/fastify-jwt#188]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Once `fast-jwt` lands a new version fixing this issue: https://github.com/nearform/fast-jwt/issues/147 remove the `JwtHeader` type definition from this library and use the one from `fast-jwt`.

**Comment by ja-bravo** [comment]
Looks like fast-jwt just landed a new version with the changes, I'll take this one if no one is working on it.

**Comment by Fdawgs** [comment]
> Looks like fast-jwt just landed a new version with the changes, I'll take this one if no one is working on it.

Go for it, thanks!

**Comment by radomird** [comment]
> Looks like fast-jwt just landed a new version with the changes, I'll take this one if no one is working on it.

I think you might need to wait a bit with this, as the changes on `fast-jwt` didn't get released yet: https://github.com/nearform/fast-jwt/issues/155

**Comment by simoneb** [comment]
we could open a PR which references the main branch of fast-jwt then once released we update it and merge it
