### ISSUE TITLE
`formatUser` with asynchronous function

### ISSUE THREAD

**Issue by onosendi** [fastify/fastify-jwt#200]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.0

### Node.js version

16.8.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

irrelevant

### Description

I'm not really sure if this is a fastify or fastify-jwt issue. I'm trying to pull data from a database via the `formatUser` option, however it seems to not like an async function. Maybe the `formatUser` option isn't even the place I should be doing this. Maybe add an `onRequest` hook and decorate there?

### Steps to Reproduce

The following returns an empty object `{}`, due to the `async` key word.

```javascript
fastify.register(FastifyJWT, {
  formatUser: async () => ({ foo: 'bar' }),
});
```

**Comment by mcollina** [comment]
> Maybe add an onRequest hook and decorate there?

That's what I'd do!
