### ISSUE TITLE
Be consistent about the hook to use for verifying the token in the examples

### ISSUE THREAD

**Issue by rluvaton** [fastify/fastify-jwt#211]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

For verifying & accessing the decoded token inside all of the routes the example uses the `onRequest` hook:

https://github.com/fastify/fastify-jwt/blob/d5fdb26b000d283712922e60580d7ca88766b011/README.md#L41-L56

But if we want to do the same for **some** of the routes, the example uses the `preValidation` hook:

https://github.com/fastify/fastify-jwt/blob/d5fdb26b000d283712922e60580d7ca88766b011/README.md#L88-L102

Is there a reason it's not consistent?

Related comment by Matteo (not mentioning by purpose to not flood his notifications if it's not already) to use `onRequest` (if I understand it correctly) https://github.com/fastify/fastify-jwt/pull/33#issuecomment-453112412

**Comment by mcollina** [comment]
I would go with `onRequest`. Would you like to send a PR?

**Comment by rluvaton** [comment]
Sure, is there a reason for that?
