### ISSUE TITLE
unable to install "fastify\jwt@5.0.0" 

### ISSUE THREAD

**Issue by BharathSH** [fastify/fastify-jwt#222]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Node.js version

15.6.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

facing below issue while installing fastify-jwt

"Could not install from "fastify\jwt@5.0.0" as it does not contain a package.json file "

### Steps to Reproduce

npm i fastify\jwt@5.0.0

**Comment by Fdawgs** [comment]
try `npm i @fastify/jwt`
