### ISSUE TITLE
Refresh Token For JWT

### ISSUE THREAD

**Issue by bigansh** [fastify/fastify-jwt#236]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

We get an option to keep the token forever or expire the token after a set period. Is there an option to refresh the token like we get in OAuth2.0?

**Comment by nerdophile** [comment]
Yep, I also need some insights on the issue mentioned above. I m trying to integrate classic access-refresh token authorization-based architecture in Fastify. I was curious if there were any methods out of the box that would be of help. Or should avoid using @fastify-jwt for this kind of implementation and build a custom API from the scratch?

**Comment by mcollina** [comment]
I don't understand the question. What's the exact flow you'd like to achieve?

**Comment by maslennikov** [comment]
@bigansh @nerdophile to implement token refresh flow you could generate another jwt token. It may contain a longer `exp` claim (a couple of weeks or whatever) and, for example, some special value in `aud` claim to prevent all other parts of your system authorizing it. This check needs to be implemented in corresponding middleware of your services. Alternatively, you could sign this refresh token with a separate signature, with its pubkey never being published to other services, so they can't verify the refresh jwt. 

When a client comes to your auth server and asks to refresh, you verify the validity of token, optionally - mark somewhere in your DB the `jti` as used to prevent the repeated token refresh, and return in response another pair of tokens.

All of this special logic belongs to your specific auth service implementation and could even be implemented without jwt whatsoever.

Hope my answer helped.

**Comment by mcollina** [comment]
Are you asking if this library could provide a higher level strategy for implementing authorization servers with the "refresh tokens" patterns?

Implementing something like https://auth0.com/blog/amp/refresh-tokens-what-are-they-and-when-to-use-them/?

I think this library should only focus on jwts.

**Comment by bigansh** [comment]
yup, got it. my questions are answered. thank you.
