### ISSUE TITLE
Decoding only the Cookie if Cookie and Regular Headers Exist

### ISSUE THREAD

**Issue by Bugs5382** [fastify/fastify-jwt#237]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

- [x] Allow cookie to be parsed and verified independent of the regular access token
- [x] Unit test to ensure everything else still works and introduce this new functionally.

### Motivation

I been working on a framework using Fastify and I got most of it done. However, when it came time to create the authentication strategy I was running into a road block with refresh tokens. When you want to implement a refresh token strategy (even a non-rotating one), the refresh token is stored inside the cookie to protect it form any surface attacks and the normal access token is sent over the response. Best practices call for both the refresh and the access token to be refreshed each time. (Each site has different implementation. This is how I am doing mine.) The normal access token has more payload information than the refresh token, typically, just something to ID the user in a unique way as once the access token expires, the refresh token which is also sent over in the response can say "hey. this user is good. go ahead and get a new access token and continue on with the request.". It can also check to make sure there is not duplicate refresh token's being used (again, a site implementation code, not related to this plugin.)

So at first I created and registered two JWT tokens with different secrets, etc. However, when I combined them together in the cookie and headers along a request the 'refresh token' would always have invalid signature because it had a different secret thus it failed. So after doing some more reading, I read that typically the same secret is used for the refresh token and access token. Now that worked, however, there was no way to say if the "cookie" token itself was (a) valid, and (b) decoded independently of the regular token, thus I create a `onlyCookie` option to be passed in the **jwtVerify** function like so:

```js
await request.jwtVerify({ onlyCookie: true })
```

or

```js
const refreshToken = await request.jwtVerify({ onlyCookie: true })
```

The latter decodes just the cookie payload.

Thus with this implementation, I can now create a viable access and refresh token strategy using Fastify and Fastify JWT.

### Example

```js
const fastify = require('fastify')()
const jwt = require('@fastify/jwt')

fastify.register(jwt, {
  secret: 'foobar',
  cookie: {
    cookieName: 'refreshToken',
  },
  sign: {
    expiresIn: '10m'
  }
})

fastify
  .register(require('@fastify/cookie'))

fastify.get('/cookies', async (request, reply) => {

  const token = await reply.jwtSign({
    name: 'foo'
  })

  const refreshToken = await reply.jwtSign({
    name: 'bar'
  }, {expiresIn: '1d'})

  reply
    .setCookie('refreshToken', refreshToken, {
      domain: 'your.domain',
      path: '/',
      secure: true, // send cookie over HTTPS only
      httpOnly: true,
      sameSite: true // alternative CSRF protection
    })
    .code(200)
    .send({token})
})

fastify.addHook('onRequest', (request) => {
    request.jwtVerify()
    request.jwtVerify({onlyCookie: true})
})

fastify.get('/verifycookie', (request, reply) => {
  reply.send({ code: 'OK', message: 'it works!' })
})

fastify.listen(3000, err => {
  if (err) throw err
})
```

**Comment by mcollina** [comment]
Thanks for reporting! I don't understand this issue, could you clarify exactly what's the ask?

**Comment by Bugs5382** [comment]
I already written he code. Trying to do the PR, however I made a mistake in the author field when uploaded. Let me employer information in the repo commit message.

In any case, I add the ```onlyCookie``` option being passed in jwtVerify so that I could decode and verify only the cookie if the cookie and the regular authentication header are sent together.  Let me do the PR and you can see it.

**Comment by mcollina** [comment]
Perfect, thx!

**Comment by Bugs5382** [comment]
#238 PR has been created. :)

**Comment by Bugs5382** [comment]
Not so good for the README on the first pass but a second pass is here:

> Setting this options to `true` will decode only the cookie in the request. This is useful for refreshToken implementations where the request typically has two tokens: token and refreshToken. The main authentication token usually has a shorter timeout and the refresh token normally stored in the cookie has a longer timeout. This allows you to check to make sure that the cookie token is still valid, as it could have a different expiring time than the main token. The payloads of the two different tokens could also be different.
