### ISSUE TITLE
decoratorName not working properly

### ISSUE THREAD

**Issue by cberescu** [fastify/fastify-jwt#240]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.3

### Plugin version

6.1.0

### Node.js version

16.15.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

It seems the decoratorName is not taken in consideration . I think the issue is from this section : 
```
, function (err, result) {
      if (err) {
        next(err)
      } else {
        const user = formatUser ? formatUser(result) : result
        request.user = user   // this should be request[decoratorName] i think 
        next(null, user)
      }
    })
```

### Steps to Reproduce

```
fastify.register(require("@fastify/jwt"), {
    secret: "somesecret",
    decoratorName: 'auth',
    cookie: {
      cookieName: 'token'
    }
  })
```

**Comment by Fdawgs** [comment]
Closed by #241
