### ISSUE TITLE
Typescript issue: No overload matches this call.

### ISSUE THREAD

**Issue by Manubi** [fastify/fastify-jwt#242]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Plugin version

6.2.1

### Node.js version

16.10.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

Hi, 
I get the TS error 
```
No overload matches this call.
  Overload 2 of 3, '(plugin: FastifyPluginAsync<FastifyJWTOptions, Server, FastifyTypeProviderDefault>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'FastifyPluginCallback<FastifyJWTOptions, Server, FastifyTypeProviderDefault>' is not assignable to parameter of type 'FastifyPluginAsync<FastifyJWTOptions, Server, FastifyTypeProviderDefault>'
```

The code  is this:
<img width="742" alt="CleanShot 2022-07-07 at 14 21 46@2x" src="https://user-images.githubusercontent.com/20935138/177771987-ed3cb53d-b29c-4a1c-a0fe-718dc7ba7f50.png">

```
import fastifyJwt, { FastifyJWTOptions } from '@fastify/jwt';
import fp from 'fastify-plugin';

export default fp<FastifyJWTOptions>(async fastify => {
  fastify.register(fastifyJwt, {
    secret: process.env.MICROSOFT_CLIENT_SECRET,
    sign: { algorithms: ['RS256'] },
  });
});
```

### Expected Behavior

I expect that the type works.

Thanks!

**Comment by mcollina** [comment]
cc @Eomm

**Comment by Uzlopak** [comment]
I could not reproduce this. I actually got a implementation error

```typescript
import fastifyJwt, { FastifyJWTOptions } from '@fastify/jwt';
import fp from 'fastify-plugin';

export default fp<FastifyJWTOptions>(async fastify => {
  fastify.register(fastifyJwt, {
    secret: process.env.MICROSOFT_CLIENT_SECRET! as string,
    sign: { algorithm: 'RS256' }, // you used algoritmhm, which is not right
  });
});
```

This transpiles well

**Comment by pbell23** [comment]
I had the same error when I forgot non null assertion when providing environment variables to secret property.

Just change `process.env.MICROSOFT_CLIENT_SECRET` to `process.env.MICROSOFT_CLIENT_SECRET! as string`

**Comment by Fdawgs** [comment]
@Manubi Did @Uzlopak's solution resolve this?
