### ISSUE TITLE
Type `Secret` does not match the secret option of ES256 (with a passphrase)

### ISSUE THREAD

**Issue by yaoandy107** [fastify/fastify-jwt#246]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

6.2.1

### Node.js version

18.3.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

When I tried to use **'ES256(with a passphrase)'** as my JWT algorithm, it showed the error **"No overload matches this call"**.
The reason that this error happens seems like the type definition of the secret option has not supported the format below:
```ts
{
  key: readFileSync(`${path.join(__dirname, 'certs')}/private.pem`),
  passphrase: 'super secret passphrase',
}
```
Below is the current definition, and it should extend a new type so it could support **ES256(with a passphrase)**'s secret option
<img width="1257" alt="Screen Shot 2022-07-13 at 4 21 18 PM" src="https://user-images.githubusercontent.com/20769836/178686315-4107838c-2fa1-48e9-855e-d2800220d0ec.png">

### Steps to Reproduce
In TypeScript:
```ts
fastify.register(fastifyJwt, {
  secret: {
    private: {
      key: readFileSync(`${path.join(__dirname, 'certs')}/private.pem`),
      passphrase: 'super secret passphrase',
    },
    public: readFileSync(`${path.join(__dirname, 'certs')}/public.pem`),
  },
  sign: { algorithm: 'ES256' },
})
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by yaoandy107** [comment]
Ok, I will send a PR later today :)
