### ISSUE TITLE
Cannot read properties of undefined (reading 'bind')

### ISSUE THREAD

**Issue by tweenietomatoes** [fastify/fastify-jwt#249]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I want to use fastify-jwt for specific routes.

Here is my plugin:

```
import fp from 'fastify-plugin';
import fastifyJwt from '@fastify/jwt';

const fastifyJWT = async (fastify, options, done) => {
    fastify.register(fastifyJwt, {
      secret: 'test123'
    });
  
    fastify.decorate("authenticate", async function(request, reply) {
      try {
        await request.jwtVerify()
      } catch (err) {
        reply.send(err)
      }
    });
    done()
  }

  export default fp(fastifyJWT, { name: 'fastifyJWT'} );

```
**_I am registering plugin in server.js:_**

`fastify.register(fastifyJWT);`

**_Here is what i get when i npm start._**

`{"level":50,"time":1659008076964,"pid":14920,"hostname":"XXX","err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'bind')","stack":"TypeError: Cannot read properties of undefined (reading 'bind')\n    at C:\\Users\\xx\\Desktop\\projects\\nodejs-app\\node_modules\\fastify\\lib\\route.js:293:27\n    at Array.map (<anonymous>)\n    at Boot.<anonymous> (C:\\Users\\xxx\\Desktop\\projeler\\nodejs-app\\node_modules\\fastify\\lib\\route.js:293:16)\n    at Object.onceWrapper (node:events:627:28)\n    at Boot.emit (node:events:525:35)\n    at C:\\Users\\xxx\\Desktop\\projeler\\nodejs-app\\node_modules\\avvio\\boot.js:160:12\n    at C:\\Users\\xxx\\Desktop\\projeler\\nodejs-app\\node_modules\\avvio\\plugin.js:275:7\n    at done (C:\\Users\\xxx\\Desktop\\projeler\\nodejs-app\\node_modules\\avvio\\plugin.js:200:5)\n    at check (C:\\Users\\xxx\\Desktop\\projeler\\nodejs-app\\node_modules\\avvio\\plugin.js:224:9)\n    at node:internal/process/task_queues:140:7"},"msg":"Cannot read properties of undefined (reading 'bind')"}`

**Comment by tweenietomatoes** [comment]
i changed 
onRequest: [fastify.authenticate] to onRequest: fastify.authenticate
and it's solved.

**Comment by clearshot-xs** [comment]
I just ran into this error as well using the example code in the readme, as @tweenietomatoes mentioned changing it from an array to a function fixes the error but the route option `onRequest` accepts a function or an array of functions.

`fastify.get(
  "/",
  {
    onRequest: fastify.authenticate
  },
  async function(request, reply) {
    return request.user
  }`

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by clearshot-xs** [comment]
Sure, I'm only about 10 minutes into a new project so it is only 2 small files. I just copied the examples from the readme and ran into this error.

app.js
```
const fastify = require("fastify")({ logger: true });

fastify.register(require('./plugins/jwt'));

fastify.get(
  "/",
  {
    onRequest: [fastify.authenticate]
  },
  async function(request, reply) {
    return request.user
  }
);

const init = async () => {
  try {
    await fastify.listen({ port: 3001 });
    console.log('Server running');
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
}
init();
```

/plugins/jwt.js
```
const fp = require("fastify-plugin");

module.exports = fp(async function(fastify, opts) {
  fastify.register(require("@fastify/jwt"), {
    secret: "supersecret"
  });

  fastify.decorate("authenticate", async function(request, reply) {
    try {
      await request.jwtVerify();
    } catch (err) {
      reply.send(err);
    }
  });
});
```

**Comment by tweenietomatoes** [comment]
Changing from [] to fastify.authenticate didn't solve the problem actually.

I startted to use "jose" jwt manually instead of fastify-jwt right now.

**Comment by clearshot-xs** [comment]
Why was this issue closed? The problem still exists... Not a very good first impression of fastify tbh.

**Comment by mcollina** [comment]
It's closed because it's not a bug and OP has decided to use a different solution.

On your example:

```js
const fastify = require("fastify")({ logger: true });

fastify.register(require('./plugins/jwt'));
fastify.register(async myRoutes (fastify) {
fastify.get(
  "/",
  {
    onRequest: [fastify.authenticate]
  },
  async function(request, reply) {
    return request.user
  }
);
})

const init = async () => {
  try {
    await fastify.listen({ port: 3001 });
    console.log('Server running');
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
}
init();
```

will fix it.

**Comment by clearshot-xs** [comment]
Thank you, it might be worth mentioning in the readme that the routes need to be registered to avoid future issues about this. I'm going to assume that OP ran into this error due to their routes not being setup correctly as well.

This might be trivial for devs familiar with fastify, but as a newcomer this was an odd error to run into.

**Comment by mcollina** [comment]
I'm aware. We can provide a better DX for this too.
