### ISSUE TITLE
Problems with RSA support

### ISSUE THREAD

**Issue by darkgl0w** [fastify/fastify-jwt#25]
---
name: 🐛 Bug report
about: Problems with RSA support
---

## 🐛 Bug Report

RSA support does not work as intended, and there are errors in the test file that lead to a bias in validating tests that shouldn't pass in the actual state of the code (Currently that's a supposition, i must dig further in the code to see if my assumptions are right concerning the tests).

## To Reproduce

create an `index.js` file like this (sorry that's not the best code but that's enough to reproduce the behavior):

```js
'use strict'

// We make promises safe.
require('make-promises-safe');

const {readFileSync} = require('fs')
const Fastify = require('fastify')

const certificates = {
  public: readFileSync('certs/public.key'),
  private: readFileSync('certs/private.key')
}

const fastify = Fastify()

fastify.register(require('fastify-jwt'), {
  secret: {
    key: certificates.private,
    passphrase: certificates.public
  },
  algorithm: 'RS256'
})

fastify.post('/token', async (request, reply) => {
  // we just return a basic token
  const payload = { foo: 'bar' }

  let token = await fastify.jwt.sign(payload)

  return { token }
})

fastify.get('/verifyOk', async (request, reply) => {
  try {
    // Should return the payload { foo: 'bar' }
    // if requested with a Bearer Auth valid token
    let token;

    if (request.headers && request.headers.authorization) {
      let parts = request.headers.authorization.split(' ')
      if (parts.length === 2) {
        token = parts[1]

        if (parts[0] !== 'Bearer') {
          throw new Error('Format is Authorization: Bearer [token]')
        }
      }
    } else {
      throw new Error('No Authorization was found in request.headers')
    }

    let decoded = await fastify.jwt.verify(token)

    return { decoded }
  } catch (error) {
    reply.code(401)
    return { error }
  }
})

fastify.get('/verifyFail', async (request, reply) => {
  // Should return the payload { foo: 'bar' }
  // if requested with a Bearer Auth valid token
  // But instead it return a 'JsonWebTokenError: invalid algorithm' error
  try {
    let decoded = await request.jwtVerify()

    return { decoded }
  } catch (error) {
    reply.code(401)

    return { error }
  }
})

fastify.listen(3000, err => {
  if (err) throw err
})
```
NB.: I used the fastify-jwt certs file (you can get the public and private key from the repo).

## Expected behavior

I would expect that the requests to localhost:3000/verifyOk and to localhost:3000/verifyFail would return the same thing but that's not the case :(

When using `request.jwtVerify()` fastify-jwt always return an Invalid algorithm error.

![screen_1539703464](https://user-images.githubusercontent.com/31093081/47027919-a92e7c00-d168-11e8-9bc9-0842ebb23ebe.png)

![screen_1539703631](https://user-images.githubusercontent.com/31093081/47028069-dda23800-d168-11e8-9e0a-1b4086538447.png)

## Your Environment

- *node version*: 10.12.0
- *fastify version*: 1.12.1
- *os*: Mac (Mojave), Windows 10 Pro N (build 1809), Linux (Archlinux)
- *fastify-jwt version*: 0.5.0

**Comment by mcollina** [comment]
Would you like to send a PR to fix this issue?

**Comment by darkgl0w** [comment]
Hi,
In the PR I submitted there is only the fix for this issue, but I would like to make some other changes in order to somehow mirror jsonwebtoken package methods (especially with how fastify-jwt manages the options) are you ok if I go further in the code refactoring in order to achieve this ?

There shouldn't be breaking changes I think, but depending on how I manage the options there can be some good practices to cover in the documentation.
