### ISSUE TITLE
Add documentation about errors thrown

### ISSUE THREAD

**Issue by silane** [fastify/fastify-jwt#258]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Add documentation about errors thrown in each functions in API Spec, especially the `fastify.jwt.verify` and `request.jwtVerify` functions. Without error document, we cannot tell what caused the verification fail (token missing? signature invalid?). Knowing the cause is necessary in many cases like customizing error response or doing fallback.

**Comment by Eomm** [comment]
Thanks for reporting!
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
