### ISSUE TITLE
Fast JWT errors thrown

### ISSUE THREAD

**Issue by wbrown766** [fastify/fastify-jwt#264]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Plugin version

6.3.2

### Node.js version

16.18.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Mint 20.03 Kernel verion 5.4.0-131-generic x86_64 bits

### Description

I guess this issue ties in with open issue #258 but I have noticed 2 other things, 1 bug and 1 suggestion.

I have been working on an API backend (putting it through it's pases) and have noticed some errors that are from Fast JWT slipping through with a 500 status code.
This has caused me to implament my own custom try catch error handling to make sure the front end gets a consistent error returned.

I have seen FAST_JWT_MALFORMED and FAST_JWT_EXPIRED but dont have time to figure out how to reproduce it at the moment (sorry).
Below is quick steps to reproduce FAST_JWT_MALFORMED.

I also would like to suggest adding a throwError boolean in the options to toggle whether errors are thrown or just returned.
I feel this would be helpful in use cases where you want to do more in your code then just return an error to the user right away, and rapping it in a try catch looks and feels hacky.

### Steps to Reproduce

package.json
```json
{
	"name": "jwt_test",
	"scripts": {
		"start": "node ./index.js"
	},
	"dependencies": {
		"@fastify/jwt": "^6.3.2",
		"fastify": "^4.9.2"
	},
	"imports": {}
}
```

index.js

```javascript
const fastifyJwt = require("@fastify/jwt");
const { default: test } = require("node:test");

const schema = {
  method: "GET",
  url: "/decode",
  schema: {
    responses: {
      200: {
        content: "application/json",
        properties: {},
      },
    },
  },
};

async function handler(req, res) {
  const jwt = await req.jwtVerify();
  res.send({ status: "NO ERRORS", jwt });
  return res;
}

const fastify = require("fastify")({
  logger: false,
});

const pluginConfig = {
  secret: "Hello world!",
  decode: {
    complete: false,
  },
  sign: {
    algorithm: "HS512",
    expiresIn: "1m",
    noTimestamp: false,
  },
  verify: {
    algorithms: "HS512",
    complete: false,
  },
};

fastify.register(fastifyJwt, pluginConfig);

fastify.get("/decode", schema, handler);

async function start() {
  try {
    await fastify.ready();
    await fastify.listen({ port: 3000, host: "127.0.0.1" });
  } catch (error) {
    fastify.log.error(error);
    process.exit(1);
  }
}
start();

let res;

//normal valid jwt
run("eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJpYXQiOjEwMDAwMDAwMDAsImV4cCI6MTAwMDAwMDAwMDB9.wkMW3__sBTCflukuOYM43bbjarbaMmC-NU7U2SbXqXLoNgJRYOP4B22ZWczSA7ArtX1_YjOXoXZtxtImujxvyQ");

//jwt with edited header
run("1eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJpYXQiOjEwMDAwMDAwMDAsImV4cCI6MTAwMDAwMDAwMDB9.wkMW3__sBTCflukuOYM43bbjarbaMmC-NU7U2SbXqXLoNgJRYOP4B22ZWczSA7ArtX1_YjOXoXZtxtImujxvyQ");

//jwt with edited payload
run("eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.1eyJ1c2VySUQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJpYXQiOjEwMDAwMDAwMDAsImV4cCI6MTAwMDAwMDAwMDB9.wkMW3__sBTCflukuOYM43bbjarbaMmC-NU7U2SbXqXLoNgJRYOP4B22ZWczSA7ArtX1_YjOXoXZtxtImujxvyQ");

async function run(jwt) {
  return await fastify
    .inject({
      method: "GET",
      url: "/decode",
      headers: { Authorization: `Bearer ${jwt}` },
    })
    .then((response) => {
      console.log(response.body);
    })
    .catch((error) => {
      console.log(error.body);
    });
}
```

### Expected Behavior

not sure but im guessing it should be something like
```json
{
  "statusCode":401,
  "code":"FST_JWT_AUTHORIZATION_TOKEN_INVALID",
  "error":"Unauthorized",
  "message":"`Authorization token is invalid: ${err.message}`"
}
````

**Comment by mcollina** [comment]
thanks for reporting! We should indeed catch those and throw the appropriate errors.


Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by wbrown766** [comment]
I think I have doen it right.
VERY new to "online" git (my first ever PR)
...well and git in general
...and well programing any and all advice, tips and or criticisms/critiques most definitley welcome.

**Comment by mcollina** [comment]
you should open the actual PR now, you only pushed a commit

**Comment by HassanBahati** [comment]
@wbrown766 @mcollina was this resolved?

**Comment by mcollina** [comment]
I don't think we'd do this after all.

**Comment by HassanBahati** [comment]
> 

alright then
