### ISSUE TITLE
Server returns 500 if token malformed. Should return 401.

### ISSUE THREAD

**Issue by khokm** [fastify/fastify-jwt#274]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Server returns 401 if token is not valid, but returns 500 if token is malformed.
How to make it also return 401 in this case?

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
