### ISSUE TITLE
Doesn't work when deconstructing or passing `jwtSign` to another function

### ISSUE THREAD

**Issue by filoozom** [fastify/fastify-jwt#29]
I'm getting the following error when I deconstruct `jwtSign` from `reply` or pass it to another function:

```
TypeError: Cannot read property 'jwtSign' of undefined
    at path\node_modules\fastify-jwt\jwt.js:148:15
    at new Promise (<anonymous>)
    at replySign (path\node_modules\fastify-jwt\jwt.js:147:14)
    at Object.postLogin (path\services\user\local.js:15:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

My service:

```js
fastify.post('/login', async function ({ body }, { jwtSign }) => {
  try {
    console.log(await jwtSign({ email: body.email }))
  } catch (err) {
    console.error(err)
  }
})
```

Same for:

```js
async function sign(jwtSign, email) {
  return jwtSign({ email })
}

fastify.post('/login', async function ({ body }, reply) => {
  try {
    console.log(await sign(reply.jwtSign, body.email))
  } catch (err) {
    console.error(err)
  }
})
```

It does work when I just use `reply.jwtSign()` directly though.

**Comment by mcollina** [comment]
Destructuring is currently not supported, as the function is not bound to the reply. It's a proper method of `reply`, as it uses `reply.request` (https://github.com/fastify/fastify-jwt/blob/8e5fd44be9758078b145e1bd7f769debecc84379/jwt.js#L160) to access the request object.

**Comment by filoozom** [comment]
I'm new to `fastify`, do you have suggestions for how to fix this in a PR?

**Comment by mcollina** [comment]
There is really nothing to fix. The reason why it does not work is that `jwtSign`, like all the methods in `reply`  are proper object methods, and they need to have a proper `this`:

```
class Something {
  constructor(v) {
    this.value = v
  }

  increase() {
    this.value++
    return value
  }
}

function fn ({ increase }) {
  increase()
}

// this will throw, as fn is removing the reference to this
fn(new Something(42))
```

All of reply methods behave in the same way. This will work:

```js
const jwtSign = reply.jwtSign.bind(reply)
```

**Comment by filoozom** [comment]
Got it, thanks!
