### ISSUE TITLE
Remove conditional `jwtDecode` decorator or fix the docs

### ISSUE THREAD

**Issue by maslennikov** [fastify/fastify-jwt#295]
Docs and code comments point that since fastify-jwt version >= 4.x.x there won't be a condition on `jwtDecode` decorator. As for now, the version is 7.0.0, and this logic is still in place.

https://github.com/fastify/fastify-jwt/blob/e13ac43609996f37609651a2b72e6be549ecf098/jwt.js#L181

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by maslennikov** [comment]
@mcollina sure, I'll prepare one
