### ISSUE TITLE
Allow a grace period for expired tokens to account for network latency

### ISSUE THREAD

**Issue by MattJustMatt** [fastify/fastify-jwt#315]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It would be nice to configure fastify-jwt to accept tokens that are ~10s expired in order to account for network latency. 

### Motivation

My client checks the expiration of the token to determine if it needs to be refreshed. If they're unlucky and make a request right before it expires, they can get denied because requests can take a few seconds to complete on slow networks. 

I could have the client handle this, but it'd be nice to allow a grace period at the server level to avoid updating apps etc...

**Comment by Eomm** [comment]
Not sure about this feature: it's like the dog chasing its own tail

- token expires at X time
- client calls at X+1 time
- with grace period=1 => all good
- with grace period=2 => current behavior

So, nothing would change IMHO.
Why not increase the token expiration time instead?

**Comment by mcollina** [comment]
you can decode the token, grab Th e expiration time, and ask for a refresh

**Comment by dhensby** [comment]
I believe this is already a feature in [fast-jwt](https://github.com/nearform/fast-jwt/tree/v3.3.2#createverifier) via `clockTolerance` option. This would be used like so:

```js
fastify.register(jwt, {
    verify: {
        clockTolerance: 10000,
    },
    ...
});
```
