### ISSUE TITLE
[Docs] Missing extractToken option

### ISSUE THREAD

**Issue by cberescu** [fastify/fastify-jwt#317]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

It seems that this option is not described in the docs. It was at some point as i found the merge containing it https://github.com/fastify/fastify-jwt/pull/178  . Is there a reason it was removed from the docs? Or I didn't check the docs good enough ?

**Comment by mcollina** [comment]
Yes, it's there in the code! Would you like to send a PR?
