### ISSUE TITLE
Repository permission issue

### ISSUE THREAD

**Issue by kibertoad** [fastify/fastify-jwt#336]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

x.x.x

### Plugin version

x.x.x

### Node.js version

x.x.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

-

### Description

I'm a member of fastify plugins team, but for whatever reason I can't push to branches within the project. Maybe plugins team is not configured to have write access?

### Expected Behavior

plugins team members can push to the repo.

**Comment by jsumners** [comment]
<img width="793" alt="Monosnap Manage access - Vivaldi 2024-05-04 09-47-53" src="https://github.com/fastify/fastify-jwt/assets/321201/469aca9b-fe28-470c-b560-be67280bd962">

What is the error?

**Comment by kibertoad** [comment]
@jsumners Thank you for checking, looks like it was WebStorm acting up. After I removed the token (that surprisingly works for other repos) and regenerated it from a scratch, it started to work.
