### ISSUE TITLE
Working example with protected routes

### ISSUE THREAD

**Issue by kokujin** [fastify/fastify-jwt#38]
Can someone point me to a complete working example showing protected routes? I couldn't get the example to work. Thanks

**Comment by mcollina** [comment]
If you are using fastify v1, you should check out https://github.com/fastify/fastify-jwt/tree/v0.8.1#usage and use v0.8.1.

**Comment by cemremengu** [comment]
@kokujin Here is an example using hooks. Let us know if that helps.

https://github.com/fastify/fastify-example-todo/blob/master/services/todo.js
