### ISSUE TITLE
typescript and http2

### ISSUE THREAD

**Issue by berrg** [fastify/fastify-jwt#45]
It seems that this plugin does not work with a server declared as http2secureserver:  

fastify.FastifyInstance<
    Http2SecureServer,
    Http2ServerRequest,
    Http2ServerResponse
  >

It it possible to change the typing so that jwt support both http and http2 server?

**Comment by mcollina** [comment]
None, just that somebody should send a fix to the types. Would you like to send a PR?

**Comment by berrg** [comment]
Ok, I will write a pull request tomorrow :-)

**Comment by berrg** [comment]
It was difficult to make a typedef that was robust against all server types.  And it seems that almost every fastify plugin which has typescript only support http server. 

So  I found a better solution, in my main script I could cast the plugin to a new server class.  Hence no tydedef rewrite is necessary.

E.g.
import * as fastifyjwt from 'fastify-jwt';
const jwthttp2 = (fastifyjwt as unknown) as fastify.Plugin<
      Http2SecureServer,
      Http2ServerRequest,
      Http2ServerResponse,
      any
    >;

**Comment by Ethan-Arrowood** [comment]
The new fastify types I am working on should support this use case.

**Comment by Ethan-Arrowood** [comment]
This can be closed with the new types from #86
