### ISSUE TITLE
fastify.jwt undefined

### ISSUE THREAD

**Issue by gandra** [fastify/fastify-jwt#54]
This code:

```
const fastify = require('fastify')();
fastify.register(require('fastify-jwt'), {
    secret: 'supersecret'
});
console.log('fastify.jwt', fastify.jwt);
```

prints:

> fastify.jwt undefined

Any idea why?

**Comment by mcollina** [comment]
You'll need to call .ready() or listen. It will be there when the server has booted. register is not blocking as it can be async.
