### ISSUE TITLE
typescript secret with public/private keys

### ISSUE THREAD

**Issue by barbieri** [fastify/fastify-jwt#60]
At https://github.com/fastify/fastify-jwt#example we have:

```js
fastify.register(jwt, {
  secret: {
    private: readFileSync(`${path.join(__dirname, 'certs')}/private.key`, 'utf8'),
    public: readFileSync(`${path.join(__dirname, 'certs')}/public.key`, 'utf8')
  },
  sign: { algorithm: 'RS256' }
})
```

However at https://github.com/fastify/fastify-jwt/blob/master/index.d.ts#L62 we have:
```typescript
declare interface FastifyJWTOptions {
  secret: jwt.Secret;
  decode?: jwt.DecodeOptions;
  sign?: jwt.SignOptions;
  verify?: jwt.VerifyOptions;
}
```

But the jwt.Secret is defined as https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsonwebtoken/index.d.ts#L111
```typescript
export type Secret = string | Buffer | { key: string; passphrase: string };
```

Please change your definition to something that allows your suggested structure:
```typescript
declare interface FastifyJWTOptions {
  secret:
    | jwt.Secret
    | {
        public: jwt.Secret;
        private: jwt.Secret;
      };
  decode?: jwt.DecodeOptions;
  sign?: jwt.SignOptions;
  verify?: jwt.VerifyOptions;
}
```

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by barbieri** [comment]
Yeah, will send it tomorrow, I was in the middle of development when I filled it. Will get back to it tomorrow

**Comment by cabelitos** [comment]
@mcollina Hey, i'm sending the fix on behalf of @barbieri, since he is too busy right now.
Thank you very much.

**Comment by barbieri** [comment]
thanks @cabelitos  :-)
