### ISSUE TITLE
Allow custom unauthorized messages

### ISSUE THREAD

**Issue by kamikazechaser** [fastify/fastify-jwt#62]
At the moment the library is using the following hard coded messages:

```
'No Authorization was found in request.headers'
'Authorization token is invalid: ' + err.message
'Authorization token expired'
```

Allow users to over ride these with their custom messages, otherwise the library can fallback to the defaults above.

**Comment by mcollina** [comment]
Would you like to send a PR? Those text should be fixed.

**Comment by kamikazechaser** [comment]
Sure

**Comment by mcchrish** [comment]
I think this should be closed already.
