### ISSUE TITLE
Accessing jwt In request And reply Objects

### ISSUE THREAD

**Issue by naseemali925** [fastify/fastify-jwt#64]
Hi,
 I am trying to access jwt in `request` and `reply` objects.
The decorators only provide the `jwtSign` on `reply` and `jwtVerify` on `request`

Any help would be appreciated.

**Comment by naseemali925** [comment]
It's Done. I Created A Decorator For Request And Response With JWT.

**Comment by Eomm** [comment]
Great!
Would you like to share your solution so anybody else could get inspiration?

**Comment by naseemali925** [comment]
Hey @Eomm 
I decorated jwt to `request` and `reply`
```js
import JWT from 'jsonwebtoken'

....

fastify.decorate('jwt',JWT);
fastify.decorateRequest('jwt',JWT);
fastify.decorateReply('jwt',JWT);

```
This way I have full control of the `jwt` instance.

**Comment by Eomm** [comment]
what was the use case?

Maybe it is worth to think to add this feature to this plugin 😃

**Comment by naseemali925** [comment]
**Use case**
Needed to use JWT decode without a secret, inside `graphql` resolvers. With `fastify-gql` I can access the `request` object through `context` provided to the resolver. And the `request` object doesn't have a `decode` method.
So I decorated the `JWT` instance to request and used `jwt.decode`. 💥
