### ISSUE TITLE
reply.send is not a function

### ISSUE THREAD

**Issue by greenpau** [fastify/fastify-jwt#65]
After adding the hook:

```
// Add hook to perform JWT verification
fastify.addHook("onRequest", async (request, reply) => {
  try {
    await request.jwtVerify()
  } catch (err) {
    reply.send(err)
  }
})
```

Received:

```
{"statusCode":500,"error":"Internal Server Error","message":"reply.send is not a function"}
```

**Comment by mcollina** [comment]
You are using fastify v1. You'll need fastify v2 to use the `'onRequest'`  hook in that way

**Comment by BrozyGL** [comment]
I'm using the fastify version on v^4.12.0 and it still gives this error

**Comment by climba03003** [comment]
The reply in `.use` is `reply.raw` in `fastify`. It is expected.
I am locking this issue and please open your own one if you have further question.
