### ISSUE TITLE
User object not declared for typescript

### ISSUE THREAD

**Issue by tuelsch** [fastify/fastify-jwt#74]
## 🐛 Bug Report

The user object (SignPayloadType) is not declared on the FastifyRequest object. I'm sending a PR to fix that.

**Comment by fox1t** [comment]
Hi. This particular fix and PR just broke all of my microservices that relies on this fastify plugin. Usually I have a custom User object that I assign to request.user. I use typing augmentation to add User to FastifyRequest:

```
declare module 'fastify' {
  interface FastifyRequest {
    user: User
  }
}
```
This worked with no problem since this PR landed. Now I am getting this error:
"Subsequent property declarations must have the same type.  Property 'user' must be of type 'SignPayloadType', but here has type 'User'."

<img width="307" alt="image" src="https://user-images.githubusercontent.com/1620916/70631523-8fce7600-1c2d-11ea-8093-a5b8a5990695.png">

Am I missing something? If not, can we leave to user space deciding custom object to use?

**Comment by mcollina** [comment]
Note that we set the user data in https://github.com/fastify/fastify-jwt/blob/f726c1f553fad4de52d75d5c6f51638301029b15/jwt.js#L253. So the typing is correct in that sense. What are you doing with your typing?

**Comment by fox1t** [comment]
Actually I have a custom handler that overwrites that property on the request object. I need some more custom props on request.user. Is it out of the scope of this plugin to allow having custom object here?

**Comment by mcollina** [comment]
I'm not sure how to do that with typescript, but I think you should be able to extend the type.

**Comment by fox1t** [comment]
I am not aware of any possible way of overriding a type declaration written like this https://github.com/fastify/fastify-jwt/blob/f726c1f553fad4de52d75d5c6f51638301029b15/index.d.ts#L58
I think we have to change this type definition since it fix it to only 3 allowed types: `object | string | Buffer`. Maybe we could allow to pass an optional generic to override this default behavior.

**Comment by fox1t** [comment]
I want to provide some context here. TypeScript allows module users to "extends" the typings shipped by the package itself or @types org. This is a very important feature and every TS advance user uses it extensively. For example, in Fastify is the main way of extending Fastify's internal objects. This one that we are talking about here, is a really good example. To augment the FastifyRequest type it's enough to add this whenever in your project (however, usually, it is done in two distinct places: inside a dedicated typings folder that respects modules structure or inside the module where you register the plugin):
```
declare module 'fastify' {
  interface FastifyRequest {
    user: User
  }
}
````
The fact that the module I am declaring is called 'fastify' (pay attention to the quotes) tells TS that i want to augment a tying of that "namespace" (I am not going to explain the differences between namespaces and modules, lets consider them same for the sake of this). As you can see on this screenshot, TS "joins" all of the declarations its find and produces the "aggregated" type:
<img width="2136" alt="image" src="https://user-images.githubusercontent.com/1620916/70811810-acea7c80-1dc6-11ea-96b0-4bb09816ca7c.png">

In this specific case, as I said, I think that the plugin consumer has to provide its own request.user object and it hasn't to be enforced by the plugin itself. In fact it is not a function declaration or some internal prop that has to be considered immutable.

Hope that now it is more clear why I am pointing this out as a typings issue.

**Comment by mcollina** [comment]
cc @Ethan-Arrowood, this is way higher from my knowledge of typescript.

**Comment by fox1t** [comment]
Any news about this?

**Comment by mcollina** [comment]
I would recommend to open a new issue to give visibility.

**Comment by bburke4** [comment]
hi @fox1t, I'm also trying to augment the type of the User property on the FastifyRequest object so that I can add my own properties. Were you able to get that working? Any guidance you could offer would be great.

**Comment by fox1t** [comment]
> hi @fox1t, I'm also trying to augment the type of the User property on the FastifyRequest object so that I can add my own properties. Were you able to get that working? Any guidance you could offer would be great.

Actually not. Since I don't have time to fix this myself, I am sticking with the old version. Would you mind to open a new issue pointing this out? You can link my comment if you think that it could be helpful. I sill think this is a "bug" in this modules types definition.

**Comment by Ethan-Arrowood** [comment]
@fox1t what do you believe is the solution here? Revert the change and instruct users to augment `request.user` themselves manually whenever they consume this plugin?

I'm going to dive deeper into the changes made now to get a better sense of whats happening.

**Comment by Ethan-Arrowood** [comment]
After visiting the source code I believe this is the correct typing. Is there a way you could improve your code on your end to better support this? 

I think a way around this is you could essentially dupe the override:
```ts
declare module 'fastify' {
  interface FastifyRequest {
    user: JWTTypes.SignPayloadType | WhateverOtherTypeYouWant
  }
}
```
Then when you consume use a type guard to check for `WhateverOtherTypeYouWant`

Unfortunately types are always tricky with payload return types

**Comment by uinz** [comment]
> I am not aware of any possible way of overriding a type declaration written like this
> 
> https://github.com/fastify/fastify-jwt/blob/f726c1f553fad4de52d75d5c6f51638301029b15/index.d.ts#L58
> 
> 
> I think we have to change this type definition since it fix it to only 3 allowed types: `object | string | Buffer`. Maybe we could allow to pass an optional generic to override this default behavior.



> I am not aware of any possible way of overriding a type declaration written like this
> 
> https://github.com/fastify/fastify-jwt/blob/f726c1f553fad4de52d75d5c6f51638301029b15/index.d.ts#L58
> 
> 
> I think we have to change this type definition since it fix it to only 3 allowed types: `object | string | Buffer`. Maybe we could allow to pass an optional generic to override this default behavior.

I try to resolve it

https://github.com/fastify/fastify-jwt/pull/120

**Comment by eziz-hudayberdiyev** [comment]
Hello guys, here is the solution:
In types declaration
`
declare module 'fastify-jwt' {
	interface FastifyJWT {
		payload: PayloadType
		user: UserType
	}
}
`

**Comment by PeacefulCosmos** [comment]
> Hello guys, here is the solution: In types declaration
> 
> ```ts
> declare module 'fastify-jwt' {
> 	interface FastifyJWT {
> 		payload: PayloadType
> 		user: UserType
> 	}
> }
> ```

it works for me!!!
