### ISSUE TITLE
Consider improve trusted documentation

### ISSUE THREAD

**Issue by guilhermemntt** [fastify/fastify-jwt#78]
Hello! I'm a bit confused about trusted tokens signature ```(request, decodedToken) => true|false|Promise<true|false>```. Trying to make it work, I realized that the return of this function is setted as ```request.user``` if it isn't an falseable value. Otherwise, if falseable, the token is blacklisted. So, wouldn't it be better if it was more documented expliciting that the returned value is assigned to```request.user``` object? I wrote some code I'd like to share to explain the situation. Thanks!
```
server.register(fastifyJwt, {
          secret: process.env.SERVER_JWT_SECRET,
          trusted: (request, decodedToken) =>
            !blacklist.some(
              blacklistedToken => blacklistedToken.jti == decodedToken.jti
            )
              ? (decodedToken as any).payload
              : false
        });
```

**Comment by mcollina** [comment]
Thanks for the issue! Would you like to send a PR to improve the docs?

**Comment by guilhermemntt** [comment]
Of course! It'd be a pleasure!

**Comment by guilhermemntt** [comment]
You're correct @salmanm. The code is clear and `trusted` should not have any effect on the forwarded result at all. I can't see any other possible reason I was getting `true` from `request.user` at the time I opened this issue, though I can't also guarantee precisely that was the case. Thanks for the review and free to undo my pull request 🙏!
