### ISSUE TITLE
Does not handle dynamic secrets

### ISSUE THREAD

**Issue by Ethan-Arrowood** [fastify/fastify-jwt#8]
As far as I can tell, `fastify-jwt` does not support callback functions as the `secret`. This behavior is supported by `express-jwt` so I think it should be supported here too. 

I'm going to attempt to add this functionality!

**Comment by mcollina** [comment]
Go ahead, it’s a useful feature!

**Comment by Ethan-Arrowood** [comment]
Okay I've spent a great deal of time researching this and understanding the pieces.

The current `fastify-jwt` purpose is to decorate the instance with JWT functions like sign, verify, and decode. Sign and verify rely on a secret. Sometimes this secret is static (no big deal). *But* in some cases the secret is dynamic, as such with the RS256 algorithm and a JSON Web Key Set (learn more [here](https://auth0.com/blog/navigating-rs256-and-jwks/)). 

The RS256 algorithm is dependent on the request and authorization token of the user. SO decorating the Fastify instance with a secret (which the current `fastify-jwt` is doing) is *not* going to work with RS256 and JWKS. 

My solution is going to be a pretty much new `fastify-jwt` that will do the following:
1. Decorate the instance with `sign`, `verify`, and `decode`. `sign` and `verify` will get the `secret` key from a callback function which is also decorated onto the fastify instance. . .
2. The `secretCallback` is going to passed `request`, `response`, and `done`. If the `fastifyJwt(options)` contains a static secret key, it will just wrap this key in the callback and ignore the parameters
3. Now, by registering `fastify-jwt` in their API, they can use the standard `register` method and 

```js
fastify.register(require('fastify-jwt'), {
  secret: 'shhImSecret'
}

fastify.get('/api', {
  beforeHandler: [
    function(request, reply, done) {
      fastify.jwt.verify('auth_token', done)
    },
    function(request, reply, done) {
      // do something with the result of verify
    }
  ]
}
```
*or*
```js
fastify.register(require('fastify-jwt'), {
  secret: (options) => {
    // do something with options
    // like make request to JSON Web Key Set uri
    return function(req, res, done) {
      // returns a function which requires access to request and such
      // for example, RS256 can now check that the Auth Token in the 
      //    request header is contained within the JWKS. This function 
      //    can now call done(...) with the result of the RS256 algorithm
    }
  }
}

fastify.get('/api', {
  beforeHandler: [
    function(request, reply, done) {
      fastify.jwt.verify(request, reply, done)
    },
    function(request, reply, done) {
      // then done param in the above .verify will be called by the 
      //   returned function from the decorated secret. Now we can
      //   do something with the result of that verification.
    }
  ]
}
```

**Comment by Ethan-Arrowood** [comment]
But now that I've typed all this out it seems as though we could just process the request header token in the beforeHandler array and pass that along to the verify function. hmmm maybe there is a slightly better way to work the dynamic use case. . . . .

**Comment by Ethan-Arrowood** [comment]
```js
fastify.register(require('fastify-jwt'), {
  secret: (options) => {
    // do something with options
    // like make request to JSON Web Key Set uri
    return function(req, res, done) {
      // returns a function which requires access to request and such
      // for example, RS256 can now check that the Auth Token in the 
      //    request header is contained within the JWKS. This function 
      //    can now call done(...) with the result of the RS256 algorithm
    }
  }
}

fastify.get('/api', {
  beforeHandler: [
    function(request, reply, done) {
      fastify.jwt.verify(request, reply, done)
    },
    function(request, reply, done) {
      // then done param in the above .verify will be called by the 
      //   returned function from the decorated secret. Now we can
      //   do something with the result of that verification.
    }
  ]
}
```

**Comment by Ethan-Arrowood** [comment]
Now I don't have a good enough understanding of every JWT possibility so I think the above method is the best way. Because now the user can define the secret function however they need to in order to process the request header or body or whatever they need access too. So it looks like the verify method needs to be overloaded. Definitely will need some tight type checking in the parameters (or maybe I could use an options object hmm)

**Comment by Ethan-Arrowood** [comment]
**Better solution** (maybe)

First: `fastify-jwt` api is **changing** 
1. removing `decode` and `secret` from decorate
2. modifying `sign` and `verify` to have the parameters: `(request, reply, done)`
3. when registering `fastify-jwt` you must pass an `options` object with a defined `secret` property
4. The `secret` property can be either a primitive `string` or a `function`.
5. If `secret` is a function, it should expect its return value to be treated as a function with the parameters `(request, reply, done)`. These parameters will come from `sign` and `verify`.
6. If `secret` is a `string` then `fastify-jwt` will wrap the `secret` in a callback function that nullifies the `request` and `reply` parameter defined in 5
7. Now this enables the developer to register `fastify-jwt` and use it however they please in any route of their choosing. 
```js
fastify.register(require('fastify-jwt'), { secret: 'shhhh' })
// or
fastify.register(require('fastify-jwt'), {
  secret: (options) => {
    // do stuff with options
    return (request, reply, done) => {
      // do stuff with request and options
    }
  }
})
// then in any route:
fastify.get('/api', {
  beforeHandler: [
    function(request, reply, done) {
      fastify.jwt.verify(request, reply, done)
    },
    function(request, reply, done) {
      // do something with result of verify
    }
  ]
}, (request, reply) {
  reply.send({ foo: 'bar' })
})
```
8. They can also implement `fastify-jwt` as a global middleware and always verify _every_ route
(I think this might be better achieved with `fastify.addHook('onRequest', ...)` but I'm not sure because I'm still learning the best flow for middlewares and such)
```js
const jwt = require('fastify-jwt')({ secret: 'shhhh' }) // or secret function

fastify.register((request, reply, next) => {
  fastify.jwt.verify(request, reply, done)
})

// and now any route should get verified:
fastify.get('/api', (request, reply) {
  reply.send({ foo: 'bar' })
})
```

I could be completely wrong (again) (for like the 100th time) but I'm feeling slightly more confident about this solution than all previous attempts. Sorry about comment spam but this is probably one of the hardest coding puzzles I've thought through and sometimes writing it all out helps a lot (even if no one is actually responding to it 😂)

**Comment by Ethan-Arrowood** [comment]
OMG I DID IT! 🎉
<img width="1440" alt="screen shot 2018-01-16 at 12 38 33 am" src="https://user-images.githubusercontent.com/16144158/34973457-9e68bc9e-fa55-11e7-90c7-017ae23791dc.png">

Works exactly like it did with all the express stuff. Now its time to clean up and commit

**Comment by bneigher** [comment]
@Ethan-Arrowood I tried to do this and it looks like the jwt headers are being stripped from the `fastifyJwtSecret` call in your branch of `node-jwks-rsa`.

Essentially the `header.alt` and `header.kid` never make it to the `secretProvider()` function call

Am I missing something?

**Comment by Ethan-Arrowood** [comment]
@bneigher are you referring to this open PR branch? https://github.com/auth0/node-jwks-rsa/pull/31

The node-jwks-rsa repo has not been well maintained so I am not sure how to best help here.

**Comment by vcanales** [comment]
> Essentially the `header.alt` and `header.kid` never make it to the `secretProvider()` function call
> 
> Am I missing something?

It's a `fastify-jwt` config issue. You have to pass the `{decode: {complete: true}}` option for the header to be handed to the function along with the payload.
