### ISSUE TITLE
Potential misinformation on cookies

### ISSUE THREAD

**Issue by kamikazechaser** [fastify/fastify-jwt#80]
From the documentation:

> Example using cookie
> 
> Storing JWT in Cookie mean that your app maybe vunerable to XSS attack and must be protected with CSRF token, consider that as a best practice...

Cookies with the httpOnly cannot be susceptible to XSS on popular browsers. You can prevent CSRF with the sameSite flag which is now [supported on popular browsers](https://caniuse.com/#feat=same-site-cookie-attribute). So a combination of properly configured httpOnly, sameSite and secure cookies make them almost bullet proof.

>  ..but storing JWT on cookies makes your REST API arent Stateless anymore...

This explicitly assumes the use of sessions which is not always the case.

**Comment by mcollina** [comment]
Would you like to send a PR to improve the docs, possibly with an example?

**Comment by kamikazechaser** [comment]
Sure, ill add some references from OWASP.

**Comment by kamikazechaser** [comment]
This may be a bit opinionated, but I added cookie support to the `req.jwtVerify` decorator since its presently only checking for the token in the authorization header. Let me know if its a fit for this plugin. Commit reference above.

Usage would be:

```
# sample cookie
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c...............
```

```js
req.jwtVerify({ cookie: true, cookieName: 'token' })
```

**Comment by mcollina** [comment]
This might be a useful addition to the library.

**Comment by Eomm** [comment]
Fixed by @kamikazechaser 

Closing
