### ISSUE TITLE
Module augmentation in TypeScript

### ISSUE THREAD

**Issue by henriqueyang** [fastify/fastify-jwt#82]
Hi guys! How can i properly use module augmentation to add authenticate decorate?

![2020-02-11_10-50](https://user-images.githubusercontent.com/38864739/74242903-7ee9c180-4cbd-11ea-83d6-68e1e7523d1c.png)

![2020-02-11_10-51](https://user-images.githubusercontent.com/38864739/74242964-9a54cc80-4cbd-11ea-9e4e-190250713070.png)

Thanks!

**Comment by mcollina** [comment]
@Ethan-Arrowood would you mind to chime in?

**Comment by Ethan-Arrowood** [comment]
@henriqueyang is `augmentation.ts` being read by your type interpreter? 

The declaration seems valid. I'd try pasting it directly in your plugin file. This will ensure it is being included by the type interpreter

**Comment by henriqueyang** [comment]
@Ethan-Arrowood I think so, vscode's intellisense was recognizing. The augmentation code was in 'src/@types' directory, but pasting it in my plugin file, like u suggested, works. Thanks!

**Comment by henriqueyang** [comment]
I properly fixed it by adding the module augmentation directory in `tsconfig.json`

![screenshot_4](https://user-images.githubusercontent.com/38864739/75095982-56917b00-5579-11ea-847d-0eed29493f8e.png)

My bad, i'm new in Typescript. Anyway, thanks guys!
