### ISSUE TITLE
I'm not sure where the problem is

### ISSUE THREAD

**Issue by Lotryas** [fastify/fastify-jwt#83]
Hello!
I need help with the implementation of the plugin. It doesn't work as intended. Probably because I didn't understand something. I'm a novice.
I did read the Docs and about encapsulation and it seems good to me. But it doesn't. So, it's sure i misunderstood something.

I have this code:

_server.js_
`fastify.register(require('./routes/users'))`

_routes/users.js_
```
module.exports = async function (fastify, options) {
  fastify.register(require('../decors/users'))
  console.log(fastify.authenticate)  // this is undefined

  fastify.route({
    method: 'POST',
    url: '/users',
    schema: {
      body: {
        type: 'object',
        required: ['username', 'email', 'password'],
        properties: {
          email: { type: 'string' },
          password: { type: 'string' },
          username: { type: 'string' }
        }
      },
      response: {
        201: {
          type: 'object',
          properties: {
            email: { type: 'string' },
            username: { type: 'string' }
          }
        }
      }
    },
    preHandler: [fastify.authenticate],
    handler: fastify.addUser
  })
}
```

_decors/users_
```
const fp = require('fastify-plugin')

module.exports = fp(async function (fastify, options) {
  fastify.register(require('fastify-jwt'), {
    secret: 'supersecret'
  })

  fastify.decorate('authenticate', async function(request, reply) {
    try {
      await request.jwtVerify()
    } catch (err) {
      reply.send(err)
    }
  })

  fastify.decorate('addUser', async function(request, reply) {
    // something
  })
})
```

I'm getting this error: Missing handler function for POST:/users route.
And that's because fastify.authenticate and fastify.addUser are undefined.
But I've registered them, no? 😕

I hope this is the place to ask for help.
Thanks in advance!

**Comment by mcollina** [comment]
You’ll need to register your route in an after block or move the register of the decorators plugin to the top level
