### ISSUE TITLE
Add ability to specify the token location in request headers

### ISSUE THREAD

**Issue by simoneb** [fastify/fastify-jwt#90]
## 🚀 Feature Proposal

Currently the default, non-configurable behavior for tokens sent with headers (meaning, not in cookies) is hardcoded to look for the token in the `Authorization` header with format `Bearer {token}`. It should be possible to specify a custom location and format for the token in the headers. For instance, a custom header, and a custom format not necessarily involving `Bearer`.

## Motivation

JWT doesn't prescribe a way to send a token to an API, so it should be possible to provide a custom location where the token is retrieved from and validated.

## Example

The custom logic should override [these lines of code](https://github.com/fastify/fastify-jwt/blob/340860ac7be7d8d10bf091ead0b8835eef7b8837/jwt.js#L205-L216), and could be provided as an option to the plugin via a callback which is used to extract the token from the request, for instance:

```
extractToken: request => token
```

**Comment by jsumners** [comment]
> JWT doesn't prescribe a way to send a token to an API...

It's outlined in https://tools.ietf.org/html/rfc7523#section-2.1

Which specifically states that the bearer JWT is to be provided as `authorization: Bearer <token>`.

**Comment by simoneb** [comment]
That is that OAuth RFC. JWTs are not necessarily used in that context. See [here](https://tools.ietf.org/html/rfc7519#section-1).

> JSON Web Token (JWT) is a compact claims representation format
   intended for space constrained environments such as HTTP
   Authorization headers and URI query parameters.

So no, the spec doesn't prescribe where you should put it.

**Comment by thomheymann** [comment]
@simoneb What's the use case for using a header other than `Authorization: Bearer`?

**Comment by simoneb** [comment]
An existing application that's sending the token in a custom request header and sending it in this way to other existing microservices. We're creating a new microservice based on fastify and we can't change the way the token is sent to the services.

**Comment by thomheymann** [comment]
Makes sense, I'll have a look at this today
