### ISSUE TITLE
Typescript fails to compile the plugin

### ISSUE THREAD

**Issue by macocha** [fastify/fastify-jwt#94]
## 🐛 Bug Report

Application that uses `fastify-jwt@2.1.0` fails to compile with typescript.

## To Reproduce

1. Install and import the module.
2. Try to compile:
```sh
npx tsc
node_modules/fastify-jwt/jwt.d.ts:77:123 - error TS2694: Namespace '"node_modules/fastify/fastify"' has no exported member 'JWTTypes'.

...

Found 2 errors.
```

## Your Environment

- *node version*: v14.2.0
- *typescript version*: 3.9.5
- *fastify version*: 3.0.0-rc.3
- *os*: Mac

**Comment by mcollina** [comment]
Can you paste your `tsconfig.json`?

**Comment by macocha** [comment]
Sure!
Nothing too exciting there. ;)

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "resolveJsonModule": true,
    "strict": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": "src"
  },
  "include": ["src"],
}
```

**Comment by mcollina** [comment]
can you also include the ts you are trying to compile? The tests are passing here.

**Comment by mcollina** [comment]
A PR to fix would also be ok.

**Comment by macocha** [comment]
Ok, I've tried to reproduce, with all the packages at their latest versions and have different issue now:

`Property 'jwtVerify' does not exist on type 'FastifyRequest<Server, IncomingMessage, RequestGenericInterface>'.` 

With a simple ts file looking like:
```
import fastify from "fastify";
import fastifyJwt from "fastify-jwt";

const server = fastify();

server.register(fastifyJwt, {
  secret: "foo",
});

server.addHook("preValidation", async (request, reply) => {
  await request.jwtVerify();
});
```

fwiw I've also started to getting similar errors on my own modules that extend `FastifyRequestInterface` on latest rc of Fastify.

**Comment by mcollina** [comment]
Those were renamed in rc.4 to FastifyReply and FastifyRequest

**Comment by macocha** [comment]
I'll PR the rename here.
